### ISSUE TITLE
random 모듈을 사용하여 Monty Hall problem 구현

### ISSUE THREAD

**Issue by ktbaek72** [Upstage-4/Monty_Hall_problem#2]
## Description
random 모듈을 사용하여 Monty Hall problem 구현

## Tasks
- [x] 반복할 횟수 입력 받기
- [x] 랜덤으로 선택하고 바꾸지 않는 경우의 확률을 출력

# Reference

**Comment by ktbaek72** [comment]
random 모듈을 사용하여 Monty Hall problem 구현하였습니다.

**Comment by Laycode00** [comment]
이슈 모두 확인했습니다. Pull request도 진행부탁드려요!
